# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sting/cmake-3.24.2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/sting/cmake-3.24.2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sting/CLionProjects/ICPC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sting/CLionProjects/ICPC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/sting/cmake-3.24.2-linux-x86_64/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sting/cmake-3.24.2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sting/CLionProjects/ICPC/CMakeFiles /mnt/c/Users/sting/CLionProjects/ICPC//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sting/CLionProjects/ICPC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_cantinaOfBabel.cpp

# Build rule for target.
run_cantinaOfBabel.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_cantinaOfBabel.cpp
.PHONY : run_cantinaOfBabel.cpp

# fast build rule for target.
run_cantinaOfBabel.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_cantinaOfBabel.cpp.dir/build.make CMakeFiles/run_cantinaOfBabel.cpp.dir/build
.PHONY : run_cantinaOfBabel.cpp/fast

#=============================================================================
# Target rules for targets named run_conquestCampaign.cpp

# Build rule for target.
run_conquestCampaign.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_conquestCampaign.cpp
.PHONY : run_conquestCampaign.cpp

# fast build rule for target.
run_conquestCampaign.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_conquestCampaign.cpp.dir/build.make CMakeFiles/run_conquestCampaign.cpp.dir/build
.PHONY : run_conquestCampaign.cpp/fast

#=============================================================================
# Target rules for targets named run_curveknights.cpp

# Build rule for target.
run_curveknights.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_curveknights.cpp
.PHONY : run_curveknights.cpp

# fast build rule for target.
run_curveknights.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_curveknights.cpp.dir/build.make CMakeFiles/run_curveknights.cpp.dir/build
.PHONY : run_curveknights.cpp/fast

#=============================================================================
# Target rules for targets named run_main.cpp

# Build rule for target.
run_main.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_main.cpp
.PHONY : run_main.cpp

# fast build rule for target.
run_main.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_main.cpp.dir/build.make CMakeFiles/run_main.cpp.dir/build
.PHONY : run_main.cpp/fast

#=============================================================================
# Target rules for targets named run_template.cpp

# Build rule for target.
run_template.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_template.cpp
.PHONY : run_template.cpp

# fast build rule for target.
run_template.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_template.cpp.dir/build.make CMakeFiles/run_template.cpp.dir/build
.PHONY : run_template.cpp/fast

#=============================================================================
# Target rules for targets named run_treehouses.cpp

# Build rule for target.
run_treehouses.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_treehouses.cpp
.PHONY : run_treehouses.cpp

# fast build rule for target.
run_treehouses.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_treehouses.cpp.dir/build.make CMakeFiles/run_treehouses.cpp.dir/build
.PHONY : run_treehouses.cpp/fast

cantinaOfBabel.o: cantinaOfBabel.cpp.o
.PHONY : cantinaOfBabel.o

# target to build an object file
cantinaOfBabel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_cantinaOfBabel.cpp.dir/build.make CMakeFiles/run_cantinaOfBabel.cpp.dir/cantinaOfBabel.cpp.o
.PHONY : cantinaOfBabel.cpp.o

cantinaOfBabel.i: cantinaOfBabel.cpp.i
.PHONY : cantinaOfBabel.i

# target to preprocess a source file
cantinaOfBabel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_cantinaOfBabel.cpp.dir/build.make CMakeFiles/run_cantinaOfBabel.cpp.dir/cantinaOfBabel.cpp.i
.PHONY : cantinaOfBabel.cpp.i

cantinaOfBabel.s: cantinaOfBabel.cpp.s
.PHONY : cantinaOfBabel.s

# target to generate assembly for a file
cantinaOfBabel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_cantinaOfBabel.cpp.dir/build.make CMakeFiles/run_cantinaOfBabel.cpp.dir/cantinaOfBabel.cpp.s
.PHONY : cantinaOfBabel.cpp.s

conquestCampaign.o: conquestCampaign.cpp.o
.PHONY : conquestCampaign.o

# target to build an object file
conquestCampaign.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_conquestCampaign.cpp.dir/build.make CMakeFiles/run_conquestCampaign.cpp.dir/conquestCampaign.cpp.o
.PHONY : conquestCampaign.cpp.o

conquestCampaign.i: conquestCampaign.cpp.i
.PHONY : conquestCampaign.i

# target to preprocess a source file
conquestCampaign.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_conquestCampaign.cpp.dir/build.make CMakeFiles/run_conquestCampaign.cpp.dir/conquestCampaign.cpp.i
.PHONY : conquestCampaign.cpp.i

conquestCampaign.s: conquestCampaign.cpp.s
.PHONY : conquestCampaign.s

# target to generate assembly for a file
conquestCampaign.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_conquestCampaign.cpp.dir/build.make CMakeFiles/run_conquestCampaign.cpp.dir/conquestCampaign.cpp.s
.PHONY : conquestCampaign.cpp.s

curveknights.o: curveknights.cpp.o
.PHONY : curveknights.o

# target to build an object file
curveknights.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_curveknights.cpp.dir/build.make CMakeFiles/run_curveknights.cpp.dir/curveknights.cpp.o
.PHONY : curveknights.cpp.o

curveknights.i: curveknights.cpp.i
.PHONY : curveknights.i

# target to preprocess a source file
curveknights.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_curveknights.cpp.dir/build.make CMakeFiles/run_curveknights.cpp.dir/curveknights.cpp.i
.PHONY : curveknights.cpp.i

curveknights.s: curveknights.cpp.s
.PHONY : curveknights.s

# target to generate assembly for a file
curveknights.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_curveknights.cpp.dir/build.make CMakeFiles/run_curveknights.cpp.dir/curveknights.cpp.s
.PHONY : curveknights.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_main.cpp.dir/build.make CMakeFiles/run_main.cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_main.cpp.dir/build.make CMakeFiles/run_main.cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_main.cpp.dir/build.make CMakeFiles/run_main.cpp.dir/main.cpp.s
.PHONY : main.cpp.s

template.o: template.cpp.o
.PHONY : template.o

# target to build an object file
template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_template.cpp.dir/build.make CMakeFiles/run_template.cpp.dir/template.cpp.o
.PHONY : template.cpp.o

template.i: template.cpp.i
.PHONY : template.i

# target to preprocess a source file
template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_template.cpp.dir/build.make CMakeFiles/run_template.cpp.dir/template.cpp.i
.PHONY : template.cpp.i

template.s: template.cpp.s
.PHONY : template.s

# target to generate assembly for a file
template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_template.cpp.dir/build.make CMakeFiles/run_template.cpp.dir/template.cpp.s
.PHONY : template.cpp.s

treehouses.o: treehouses.cpp.o
.PHONY : treehouses.o

# target to build an object file
treehouses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_treehouses.cpp.dir/build.make CMakeFiles/run_treehouses.cpp.dir/treehouses.cpp.o
.PHONY : treehouses.cpp.o

treehouses.i: treehouses.cpp.i
.PHONY : treehouses.i

# target to preprocess a source file
treehouses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_treehouses.cpp.dir/build.make CMakeFiles/run_treehouses.cpp.dir/treehouses.cpp.i
.PHONY : treehouses.cpp.i

treehouses.s: treehouses.cpp.s
.PHONY : treehouses.s

# target to generate assembly for a file
treehouses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_treehouses.cpp.dir/build.make CMakeFiles/run_treehouses.cpp.dir/treehouses.cpp.s
.PHONY : treehouses.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run_cantinaOfBabel.cpp"
	@echo "... run_conquestCampaign.cpp"
	@echo "... run_curveknights.cpp"
	@echo "... run_main.cpp"
	@echo "... run_template.cpp"
	@echo "... run_treehouses.cpp"
	@echo "... cantinaOfBabel.o"
	@echo "... cantinaOfBabel.i"
	@echo "... cantinaOfBabel.s"
	@echo "... conquestCampaign.o"
	@echo "... conquestCampaign.i"
	@echo "... conquestCampaign.s"
	@echo "... curveknights.o"
	@echo "... curveknights.i"
	@echo "... curveknights.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... template.o"
	@echo "... template.i"
	@echo "... template.s"
	@echo "... treehouses.o"
	@echo "... treehouses.i"
	@echo "... treehouses.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

